dist: xenial

language: python

cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install codecov tox-travis

script:
  - tox

after_success:
  - codecov

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      python:
        - 3.7
      script:
        - tox -e lint
