name: CI
on: pull_request
jobs:
  check:
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Run check
        run: |
          pip install --requirement requirements/testing.txt
          make check
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Run lint
        run: |
          pip install --requirement requirements/testing.txt
          make lint
  test:
    name: Test - Python ${{ matrix.python }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python:
          - '3.5'
          - '3.6'
          - '3.7'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Run tests
        run: |
          PYTHON_VERSION="${{ matrix.python }}"
          pip install --requirement requirements/testing.txt
          make test-report
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
